export const ACTION_ICON = {
  DOWNLOAD: 'lucide:download',
  UPLOAD: 'lucide:upload',
  ADD: 'lucide:plus',
  EDIT: 'lucide:edit',
  DELETE: 'lucide:trash-2',
  REFRESH: 'lucide:refresh-cw',
  SEARCH: 'lucide:search',
  FILTER: 'lucide:filter',
  MORE: 'lucide:ellipsis-vertical',
  VIEW: 'lucide:eye',
  COPY: 'lucide:copy',
  GRID: 'lucide:grid-2x2-plus',
  BRIEFCASE: 'lucide:briefcase',
  AUDIT: 'ant-design:audit-outlined',
  UNDO: 'ant-design:undo-outlined',
  LOG: 'material-symbols-light:docs-outline',
};
